language: node_js
node_js:
- '0.12.0'
- '5.8.0'

before_install:
- bash deploy/install.sh | sh

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

after_success:
- bash deploy/deploy.sh | sh
